/*
 * This source file was generated by the Gradle 'init' task
 */
package com.meshtier;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class App {
    
    private static final String VERSION = "1.0.1";
    private static final String COLOR = "green";
    
    @GetMapping("/version")
    public String getVersion() {
        return VERSION;
    }
    
    @GetMapping("/color")
    public String getColor() {
        return COLOR;
    }

    @GetMapping("/healthz")
    public String healthz() {
        return "ok";
    }
    
    @GetMapping("/")
    public VersionInfo getInfo() {
        return new VersionInfo(VERSION, COLOR);
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
    
    // Inner class for combined response
    public static class VersionInfo {
        private String version;
        private String color;
        
        public VersionInfo(String version, String color) {
            this.version = version;
            this.color = color;
        }
        
        public String getVersion() {
            return version;
        }
        
        public String getColor() {
            return color;
        }
    }
}
